# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/vscode_anki_repo',
                'doc_host': 'https://rleyvasal.github.io',
                'git_url': 'https://github.com/rleyvasal/vscode_anki_repo',
                'lib_path': 'vscode_anki_repo'},
  'syms': {'vscode_anki_repo.core': {'vscode_anki_repo.core.foo': ('core.html#foo', 'vscode_anki_repo/core.py')}}}